spring.datasource.url=jdbc:mysql://localhost:3306/welltrack
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.password=Bcrypt
jwt.secret=welltrackSuperSecureSecretKey1234567890!@#ABCDEF